project_id = "hero"

[functions.peek-invite]
verify_jwt = false

[functions.create-invite]
verify_jwt = true

[functions.accept-invite]
verify_jwt = true

[functions.start-session]
verify_jwt = true

[functions.submit-session]
verify_jwt = true

[functions.admin-scenario]
verify_jwt = true

[functions.manager-user-action]
verify_jwt = true

[functions.nickname-action]
verify_jwt = true
